### ISSUE TITLE
negative values passed to chart

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Visualizations#35]
### Actual behavior
Negative values are passed to the charting library causing hundreds of errors to be logged to the console.

### Steps to reproduce behavior
Identified while scaling the person report on the data sources tab.

![image](https://user-images.githubusercontent.com/6586384/48364272-fd4c5380-e675-11e8-8259-9a339a0ebf8b.png)

**Comment by chrisknoll** [comment]
Are you certain this is an issue with the chart library and not invalid input into the parameters?  I'm using the local test cases, here is the results after resizing:

![image](https://user-images.githubusercontent.com/6818777/49032098-be3ff700-f179-11e8-8cc4-10fd3ee95982.png)

Resized smaller:
![image](https://user-images.githubusercontent.com/6818777/49032127-d0219a00-f179-11e8-97ea-7232d7fde2b3.png)

Console log (shows no errors on resize):

![image](https://user-images.githubusercontent.com/6818777/49032167-edeeff00-f179-11e8-9411-0fd7758bf248.png)

This is most likely a problem with how Atlas is trying to infer the width/height from the client resulting in some kind of dirty values that should be handled before passing into the chart library.
