### ISSUE TITLE
incorrect negative translation on histogram

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/Visualizations#36]
![image](https://user-images.githubusercontent.com/6586384/49039670-6bbd0580-f18e-11e8-968c-6360c786a834.png)

Histogram translates positive values on the negative side of the X axis.  

![image](https://user-images.githubusercontent.com/6586384/49039836-e84fe400-f18e-11e8-9370-769913a2e8fe.png)

Sample data:

[{"x":62,"dx":1,"y":0},{"x":61,"dx":1,"y":0},{"x":60,"dx":1,"y":0},{"x":50,"dx":1,"y":0},{"x":49,"dx":1,"y":0},{"x":48,"dx":1,"y":0},{"x":47,"dx":1,"y":0},{"x":41,"dx":1,"y":0},{"x":38,"dx":1,"y":0},{"x":37,"dx":1,"y":0},{"x":36,"dx":1,"y":0},{"x":32,"dx":1,"y":0},{"x":27,"dx":1,"y":0},{"x":26,"dx":1,"y":0},{"x":25,"dx":1,"y":0},{"x":23,"dx":1,"y":0},{"x":15,"dx":1,"y":0},{"x":12,"dx":1,"y":0},{"x":10,"dx":1,"y":1},{"x":8,"dx":1,"y":1},{"x":7,"dx":1,"y":1},{"x":5,"dx":1,"y":1},{"x":4,"dx":1,"y":2},{"x":3,"dx":1,"y":2},{"x":2,"dx":1,"y":67},{"x":1,"dx":1,"y":91}]

See: https://github.com/OHDSI/Atlas/issues/851

**Comment by chrisknoll** [comment]
This is what appears in the test plot when using the sample data provided:

![image](https://user-images.githubusercontent.com/6818777/49040235-fce0ac00-f18f-11e8-94b3-41f310f11407.png)

All the bars appear on the positive side of the Y axis.  Something specific to Atlas is at play here.
